[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"


[project]
name = "gumpgpd"
version = "1.0.1+local"
description = "GPD analysis tools for DVCS, DVMP, and lattice inputs"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

authors = [
  { name = "Yuxun Guo", email = "youuungx@gmail.com" }
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "iminuit",
  "joblib",
  "mpmath",
  "numba",
  "numpy",
  "pandas",
  "scipy",
]


[tool.hatch.build]
license-files = ["LICEN[CS]E*"]


[tool.hatch.build.targets.wheel]
packages = ["src/gumpgpd"]
